const STRATEGY = {
  RSI_PERIOD: 14,
  RSI_OVERSOLD: 40,
  RSI_OVERBOUGHT: 70,

  BOLLINGER_PERIOD: 20,
  BOLLINGER_STD_DEV: 2,

  VOLUME_THRESHOLD: 1.5,

  STOP_LOSS_PCT: -2,
  TAKE_PROFIT_PCT: 5,
  MAX_HOLD_HOURS: 4,

  CANDLE_INTERVAL: 'minutes/5',
  CANDLE_COUNT: 200,
  SCAN_INTERVAL_MS: 10000,
};

module.exports = { STRATEGY };
